import {
  siIcloud,
  siNetflix,
  siSpotify,
  siYoutube,
  siApplemusic,
  siAppletv,
  siHbo,
  siMax,
  siAudible,
  siTwitch,
  siGithub,
  siGitlab,
  siBitbucket,
  siVercel,
  siNetlify,
  siGithubcopilot,
  siSupabase,
  siFirebase,
  siDigitalocean,
  siRailway,
  siCloudways,
  siGoogledrive,
  siGooglecloud,
  siCloudflare,
  siFigma,
  siWebflow,
  siWordpress,
  siSquarespace,
  siShopify,
  siNotion,
  siObsidian,
  siEvernote,
  siTodoist,
  siTrello,
  siAsana,
  siJira,
  siClickup,
  siCalendly,
  siGrammarly,
  siLinear,
  siGooglecalendar,
  siGmail,
  siDiscord,
  siZoom,
  siAnthropic,
  siClaude,
  siGooglegemini,
  siStripe,
  siPaypal,
  siCoinbase,
  siBinance,
  siMedium,
  siSubstack,
  siPatreon,
  siSteam,
  siEpicgames,
  siPlaystation,
  siDuolingo,
  siCoursera,
  siUdemy,
  siSkillshare,
  siNamecheap,
  siGodaddy,
  siNordvpn,
  siExpressvpn,
  siLastpass,
  siBitwarden,
  si1password,
  siStrava,
  siPeloton,
  siHeadspace,
  siUber,
  siUbereats,
  siDoordash,
  siAirbnb,
  siInstacart,
  siDropbox,
  siMailchimp,
  siSnapchat,
  siX,
  siInstagram,
  siFacebook,
  siTiktok,
  siReddit,
  siPinterest,
  siWhatsapp,
  siTelegram,
  siSignal,
  siThreads,
  siMastodon,
  siSoundcloud,
  siTidal,
  siCrunchyroll,
  siParamountplus,
  siPlex,
  siVimeo,
  siDailymotion,
  siKofi,
  siBuymeacoffee,
  siGumroad,
  siEtsy,
  siEbay,
  siAliexpress,
  siIkea,
  siBox,
  siMega,
  siProton,
  siProtonmail,
  siZoho,
  siHubspot,
  siIntercom,
  siZendesk,
  siAirtable,
  siMiro,
  siLoom,
  siFramer,
  siWix,
  siGhost,
  siPostman,
  siJetbrains,
  siIntellijidea,
  siPycharm,
  siSublimetext,
  siReplit,
  siCodesandbox,
  siStackoverflow,
  siNpm,
  siDocker,
  siKubernetes,
  siTerraform,
  siGrafana,
  siDatadog,
  siSentry,
  siMongodb,
  siPostgresql,
  siMysql,
  siRedis,
  siPlanetscale,
  siNeon,
  siRender,
  siFlydotio,
  siGoogleanalytics,
  siMixpanel,
  siPosthog,
  siHotjar,
  siConfluence,
  siGooglemeet,
  siWebex,
  siWechat,
  siLine,
  siRobinhood,
  siWise,
  siRevolut,
  siMonzo,
  siCashapp,
  siVenmo,
  siKlarna,
  siQuickbooks,
  siXero,
  siGooglephotos,
  siGoogleads,
  siGoogleplay,
  siAppstore,
  siMubi,
  siLetterboxd,
  siKakaotalk,
} from "simple-icons";

export interface Brand {
  slug: string;
  title: string;
  hex: string;
  path: string;
}

interface RawIcon {
  slug: string;
  title: string;
  hex: string;
  path: string;
}

const RAW: RawIcon[] = [
  siIcloud,
  siNetflix,
  siSpotify,
  siYoutube,
  siApplemusic,
  siAppletv,
  siHbo,
  siMax,
  siAudible,
  siTwitch,
  siGithub,
  siGitlab,
  siBitbucket,
  siVercel,
  siNetlify,
  siGithubcopilot,
  siSupabase,
  siFirebase,
  siDigitalocean,
  siRailway,
  siCloudways,
  siGoogledrive,
  siGooglecloud,
  siCloudflare,
  siFigma,
  siWebflow,
  siWordpress,
  siSquarespace,
  siShopify,
  siNotion,
  siObsidian,
  siEvernote,
  siTodoist,
  siTrello,
  siAsana,
  siJira,
  siClickup,
  siCalendly,
  siGrammarly,
  siLinear,
  siGooglecalendar,
  siGmail,
  siDiscord,
  siZoom,
  siAnthropic,
  siClaude,
  siGooglegemini,
  siStripe,
  siPaypal,
  siCoinbase,
  siBinance,
  siMedium,
  siSubstack,
  siPatreon,
  siSteam,
  siEpicgames,
  siPlaystation,
  siDuolingo,
  siCoursera,
  siUdemy,
  siSkillshare,
  siNamecheap,
  siGodaddy,
  siNordvpn,
  siExpressvpn,
  siLastpass,
  siBitwarden,
  si1password,
  siStrava,
  siPeloton,
  siHeadspace,
  siUber,
  siUbereats,
  siDoordash,
  siAirbnb,
  siInstacart,
  siDropbox,
  siMailchimp,
  siSnapchat,
  siX,
  siInstagram,
  siFacebook,
  siTiktok,
  siReddit,
  siPinterest,
  siWhatsapp,
  siTelegram,
  siSignal,
  siThreads,
  siMastodon,
  siSoundcloud,
  siTidal,
  siCrunchyroll,
  siParamountplus,
  siPlex,
  siVimeo,
  siDailymotion,
  siKofi,
  siBuymeacoffee,
  siGumroad,
  siEtsy,
  siEbay,
  siAliexpress,
  siIkea,
  siBox,
  siMega,
  siProton,
  siProtonmail,
  siZoho,
  siHubspot,
  siIntercom,
  siZendesk,
  siAirtable,
  siMiro,
  siLoom,
  siFramer,
  siWix,
  siGhost,
  siPostman,
  siJetbrains,
  siIntellijidea,
  siPycharm,
  siSublimetext,
  siReplit,
  siCodesandbox,
  siStackoverflow,
  siNpm,
  siDocker,
  siKubernetes,
  siTerraform,
  siGrafana,
  siDatadog,
  siSentry,
  siMongodb,
  siPostgresql,
  siMysql,
  siRedis,
  siPlanetscale,
  siNeon,
  siRender,
  siFlydotio,
  siGoogleanalytics,
  siMixpanel,
  siPosthog,
  siHotjar,
  siConfluence,
  siGooglemeet,
  siWebex,
  siWechat,
  siLine,
  siRobinhood,
  siWise,
  siRevolut,
  siMonzo,
  siCashapp,
  siVenmo,
  siKlarna,
  siQuickbooks,
  siXero,
  siGooglephotos,
  siGoogleads,
  siGoogleplay,
  siAppstore,
  siMubi,
  siLetterboxd,
  siKakaotalk,
];

export const BRANDS: Brand[] = RAW.map((i) => ({
  slug: i.slug,
  title: i.title,
  hex: i.hex,
  path: i.path,
})).sort((a, b) => a.title.localeCompare(b.title));

export const BRAND_MAP: Record<string, Brand> = Object.fromEntries(
  BRANDS.map((b) => [b.slug, b])
);

/** A `logo` value of `letter:X` forces a monogram tile showing X. */
export const LETTER_PREFIX = "letter:";

/** 0–9 then A–Z, for the monogram picker. */
export const MONOGRAM_CHARS: string[] = [
  ..."0123456789".split(""),
  ..."ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),
];

export function letterFromLogo(logo?: string): string | null {
  if (logo && logo.startsWith(LETTER_PREFIX)) {
    return logo.slice(LETTER_PREFIX.length).charAt(0).toUpperCase() || null;
  }
  return null;
}

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

/**
 * Best-effort brand match from a free-text subscription name.
 * Matches the whole name or its first word to a brand title (no fuzzy
 * substring, to avoid e.g. "Maximus" → Max). Returns a slug or null.
 */
export function detectBrandSlug(name: string): string | null {
  if (!name) return null;
  const whole = norm(name);
  const exact = BRANDS.find((b) => norm(b.title) === whole);
  if (exact) return exact.slug;
  const first = norm(name.split(/\s+/)[0] ?? "");
  if (first.length >= 2) {
    const byFirst = BRANDS.find((b) => norm(b.title) === first);
    if (byFirst) return byFirst.slug;
  }
  return null;
}
